Add `derive_predictors` module + test inference
BasisResearch/collab-creatures pull request #114
Opened 2024-08-29 18:11 UTC by PalkaPuri

2024-08-30 14:35 UTC, rfl-urbaniak requested changes
Looks pretty cool, this is becoming fun!

Fixed small interpunction issues, 
added time to derivation logging.
____
derive_predictors_and_scores: the distinction between predictors and scores could be better explained, please also add example for `score_kwargs` the way you added them for `predictor_kwargs`. Otherwise, the users might be confused and have the impression of unecessary duplication.
___

CI lint test fails on the runner, please fix.
____
The notebook produces warnings:

 UserWarning: Using existing velocity data.
                Delete corresponding columns from foragersDF to re-calculate velocity values.

but it's not clear these should be triggered just because you do multiple velocity predictors, please reflect on this and consider modifying the warning trigger.
___

2024-08-30 14:51 UTC, rfl-urbaniak commented
tests and lints now seem to pass once I pushed my fixes

2024-09-04 21:29 UTC, PalkaPuri commented
Thanks @rfl-urbaniak ! 

- I added an explanation and example for `score_kwargs` in the docstring to make it more clear
- I decided to remove the duplicate velocity warning entirely. We are saving the velocity values under column names that indicate what parameters were used to compute it (i.e. `f"v_dt={dt}"`), and the functions only reuse the velocities if the dt matches -- these checks prevent erroneous computations and so I don't think a UserWarning is necessary. Have a look at derive_predictors.ipynb and let me know what you think!

2024-09-04 23:29 UTC, rfl-urbaniak approved these changes

2024-09-04 23:29 UTC, merged