Added empty __init__.py file to collab/foraging
BasisResearch/collab-creatures pull request #87
Opened 2024-07-05 21:40 UTC by PalkaPuri

scripts in collab/foraging were not being recognized on my computer due to missing "__init__.py" file. Added for robustness

2024-07-08 17:11 UTC, rfl-urbaniak commented
You also included changes to data files for locust/ds - these changes should've been discarded. But this also points out to an issue that needs to be discussed, i.e. that processed model data are now not being gitignored. This makes sense if we want the users to easily access them, but the downside is we need to pay attention so somebody else's re-runs don't get merged into main (just to avoid potential problems downstream). For now please remove your changes to these files from this PR (and presumably don't commit such changes in future PRs) and move on so that you're not blocked. I'll think of a better way to handle this.

2024-07-08 17:16 UTC, rfl-urbaniak requested changes
A small file change removal, see my previous comment.

2024-07-08 17:35 UTC, PalkaPuri commented
Whoops, did not realize that the locust/ds files were also changed. Fixed now.

2024-07-09 16:21 UTC, rfl-urbaniak approved these changes

2024-07-09 16:21 UTC, merged